config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
  get 'flats/:id', to: 'flats#show', as: :flat
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  FLATS_URL = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
  before_action :set_flats

  def index
    # url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    # @flats = JSON.parse(URI.open(url).read)
  end

  def show
    # url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    # flats = JSON.parse(URI.open(url).read)
    @flat = @flats.find { |flat| flat['id'] == params[:id].to_i }
  end

  private

  def set_flats
    @flats = JSON.parse(URI.open(FLATS_URL).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>
  <% @flats.each do |flat| %>
    <h2> <%= flat['name'] %></h2>
    <p><%= flat['price'] %> - <%= flat['priceCurrency'] %></p>
    <%= image_tag flat['imageUrl'], alt: flat['name'], height: 200 %>
    <%= link_to 'See details', flat_path(flat['id']) %>
<% end %>

app/views/flats/show.html.erb
<h2><%= @flat['name'] %></h2>
<p><%= @flat['price'] %></p>
<p><%= @flat['priceCurrency'] %></p>
<%= image_tag @flat['imageUrl'], alt: @flat['name'], height: 300 %>
<br>
<%= link_to 'Back', root_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>